from snakemake.utils import min_version
min_version("8.0")

import os

configfile: "../config/config.yaml"

#if not os.path.exists(config["outdir"]):
#    os.makedirs(config["outdir"])

SAMPLES, = glob_wildcards(os.path.join(config["reads"],"{sample}_1.fastq.gz"))

include: "rules/preprocessing.smk"
include: "rules/assembly.smk"
include: "rules/binning.smk"
include: "rules/refine_bins.smk"
include: "rules/phages.smk"

rule all:
    input:
        expand("out/{sample}/phage_analysis/genomad", sample = SAMPLES)
    default_target: True
