# slurm resource configuration
#executor: slurm
executor: cluster-generic
cluster-generic-submit-cmd: "sbatch"

# Resources to use if not otherwise specified    
default-resources:
  - mem_mb=16000
  - runtime=1440
  - cores=24
  - slurm_account=sahlab

jobs: 20
latency-wait: 60 
use-conda: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy

set-resources:
    host_removal:
        mem: 50G
        cpus_per_task: 8
    spades:
        mem: 512G
        cpus_per_task: 8
        time: 1440
    genomad:
        mem: 64G
    checkm:
        mem: 50G

        
