# slurm resource configuration
executor: slurm
#executor: cluster-generic
#cluster-generic-submit-cmd: "sbatch"

# Resources to use if not otherwise specified    
default-resources:
  - mem_mb=16000
  - runtime=1440
  - cores=24
  - slurm_account=sahlab

jobs: 20
latency-wait: 60 
use-conda: True
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
#restart-times: 1

set-resources:
    host_removal:
        mem: 50G
        cpus_per_task: 16
    spades:
        mem: 512G
        cpus_per_task: 12
        time: 400 
    genomad:
        mem: 200G
    checkm:
        mem: 50G
    cat:
        mem: 70G

        
