reads: "reads"
outdir: "out"

fastq_names_1: "{sample}_1.fastq.gz"
fastq_names_2: "{sample}_2.fastq.gz"
fastp_min_sequence_length: 120 

human_ref: "/ref/sahlab/data/GRCh38.fna.gz"
genomad_database: "/ref/sahlab/data/viral_analysis_DBs/genomad_DBs/genomad_db"
bakta_database: "/ref/sahlab/data/bakta_db"
cat_database: "/ref/sahlab/data/CAT_prepare_20210107"
checkv_database: "/ref/sahlab/data/viral_analysis_DBs/checkV_DB/checkv-db-v1.4"
